- id: '1774952623950'
  alias: Start Mqtt ved restart
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.trigger_mqtt
    data: {}
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: input_boolean.turn_off
    metadata: {}
    target:
      entity_id: input_boolean.trigger_mqtt
    data: {}
  mode: single
