- platform: group
  unique_id: Markise
  name: Markise
  entities:
    - cover.markise_venstre
    - cover.markise_hoyre

- platform: template
  covers:
    garasje:
      unique_id: garasje_cover
      device_class: garage
      friendly_name: "Garasje"
      value_template: >
        {% if is_state('input_boolean.garasje_apen', 'on') %}open{% else %}closed{% endif %}
      open_cover:
        - action: button.press
          target:
            entity_id: button.garasje_apner
        - action: input_boolean.turn_on
          target:
            entity_id: input_boolean.garasje_apen
      close_cover:
        - action: button.press
          target:
            entity_id: button.garasje_apner
        - action: input_boolean.turn_off
          target:
            entity_id: input_boolean.garasje_apen
      stop_cover:
        action: button.press
        target:
          entity_id: button.garasje_apner

