kjokken_vanning:
  name: Kjøkken Vanning
  capabilities:
    onoff: switch.kjokken_vanning
    measure_water: sensor.water_consumption_garden
    measure_generic: sensor.kjokken_vanning_flow
stue_piano_stikkontakt:
  name: Stue Piano Stikkontakt
  capabilities:
    onoff: switch.stue_piano_stikkontakt
    measure_current: sensor.stue_piano_stikkontakt_current
    measure_power: sensor.stue_piano_stikkontakt_power
    meter_power: sensor.stue_piano_stikkontakt_energy
    measure_voltage: sensor.stue_piano_stikkontakt_voltage
mikrobolgovn:
  name: Mikrobølgeovn
  capabilities:
    onoff: switch.mikrobolgeovn
    measure_current: sensor.mikrobolgeovn_current
    measure_power: sensor.mikrobolgeovn_power
    measure_voltage: sensor.mikrobolgeovn_voltage
pappa_kontor_stikkontakt:
  name: Pappa Kontor Stikkontakt
  capabilities:
    onoff: switch.pappa_kontor_stikkontakt
    measure_current: sensor.pappa_kontor_stikkontakt_current
    measure_power: sensor.pappa_kontor_stikkontakt_power
    measure_voltage: sensor.pappa_kontor_stikkontakt_voltage
pappa_soverom_stikkontakt:
  name: Pappa Soverom Stikkontakt
  capabilities:
    onoff: switch.pappa_soverom_stikkontakt
    measure_current: sensor.pappa_soverom_stikkontakt_current
    measure_power: sensor.pappa_soverom_stikkontakt_power
    measure_voltage: sensor.pappa_soverom_stikkontakt_voltage
tv_stikkontakt:
  name: Tv Stikkontakt
  capabilities:
    onoff: switch.tv_stikkontakt
    measure_current: sensor.tv_stikkontakt_current
    measure_power: sensor.tv_stikkontakt_power
    measure_voltage: sensor.tv_stikkontakt_voltage
varmtvannsbereder:
  name: Varmtvannsbereder
  capabilities:
    measure_current: sensor.varmtvann_current
    measure_power: sensor.varmtvann_power
    measure_voltage: sensor.varmtvann_voltage
vindusensor_venstre:
  name: Vindusensor Venstre
  capabilities:
    alarm_contact: binary_sensor.vindusensor_venstre
    alarm_motion: binary_sensor.vindusensor_venstre_acceleration
    measure_temperature: sensor.vindusensor_venstre_temperature_2
plantesensor:
  name: Plantesensor
  capabilities:
    measure_temperature: sensor.plantesensor_temperature
    measure_humidity.humid1: sensor.plantesensor_humidity
    measure_humidity.humid2: sensor.plantesensor_soil_moisture
    measure_battery: sensor.plantesensor_battery
    alarm_generic: binary_sensor.plantesensor_dry
vannventil_kjokken_hass:
  name: Kjøkken Vannventil Hass
  capabilities:
    meter_water: sensor.kjokken_vannventil_vannmaler

vannventil_veranda_blomster_hass:
  name: Veranda Blomster Vannventil Hass
  capabilities:
    meter_water: sensor.veranda_blomster_vannventil_vannmaler

vannventil_veranda_bed_hass:
  name: Veranda Bed Vannventil Hass
  capabilities:
    meter_water: sensor.veranda_bed_vannventil_vannmaler

vannmaler_hass:
  name: Vannmåler Hass
  capabilities:
    meter_water: sensor.my_water_grip_total_volume_m3








aqara_fp2_pult:
  name: Aqara FP2 Pult
  capabilities:
    alarm_motion: binary_sensor.aqara_fp2_pult
    measure_luminance: sensor.aqara_fp2_lys
    
    
    
do_klimasensor:
  name: Do Klimasensor
  capabilities:
    measure_temperature: sensor.everything_presence_one_temperature
    measure_humidity: sensor.everything_presence_one_humidity

    
    
everything_presence_one:
  name: Everything Presence One
  capabilities:
    alarm_motion.motion: binary_sensor.everything_presence_one_occupancy
    alarm_motion.mmwave: binary_sensor.everything_presence_one_mmwave
    alarm_motion.pir: binary_sensor.everything_presence_one_pir
    measure_luminance: sensor.everything_presence_one_illuminance
    measure_temperature: sensor.everything_presence_one_temperature
    measure_humidity: sensor.everything_presence_one_humidity
