#########################################
#         LYS GRUPPER                   #
#########################################

- platform: group
  name: Sebastian Taklampe
  unique_id: sebastian_taklampe
  entities:
    - light.taklampe_1
    - light.taklampe_2
    - light.taklampe_3
    - light.taklampe_4

#########################################
#         LYS GRUPPER ROM               #
#########################################

- platform: group
  name: Kjøkken Lys
  unique_id: kjokken_lys
  entities:
    - light.benkbelysning
    - light.kjokken_spot_1
    - light.kjokken_spot_2
    - light.kjokken_matbord
    - light.trappeskaplampe
    - light.vaskehall_taklampe

- platform: group
  name: Stue Lys
  unique_id: stue_lys
  entities:
    - light.taklist
    - light.stalampe
    - light.stalampe_hjorne
    - light.stalampe_piano
    - light.peislampe
    - light.skjenklampe
    - light.sofabord
    - light.gronn_sofalampe

- platform: group
  name: Soverom Lys
  unique_id: soverom_lys
  entities:
    - light.overskap
    - light.sideskap
    - light.nattbordlampe
    - light.nattlampe_ned
    - light.nattlampe_opp
    - light.vindulampe
    - light.taklampe_1

- platform: group
  name: Inngang Lys
  unique_id: inngang_lys
  entities:
    - light.inngang_taklampe
    - light.inngang_bordlampe

- platform: group
  name: Ute Lys
  unique_id: ute_lys
  entities:
    - light.utelys_inngang
    - light.bodlampe

- platform: group
  name: Pult Lys
  unique_id: pult_lys
  entities:
    - light.pultlampe
    - light.pultskjermer
    - light.oljelampe_pc

- platform: group
  name: Veranda Lys
  unique_id: veranda_lys
  entities:
    - light.verandalampe_hoyre
    - light.verandalampe_venstre

- platform: group
  name: Vaskegang Lys
  unique_id: vaskegang_lys
  entities:
    - light.vaskehall_taklampe
    - light.trappeskaplampe

- platform: group
  name: Cybele Soverom Lys
  unique_id: cybele_soverom_lys
  entities:
    - light.cybele_taklampe

- platform: group
  name: Rune Soverom Lys
  unique_id: rune_soverom_lys
  entities:
    - light.rune_taklampe
    - light.toyskap

- platform: group
  name: Trappegang Lys
  unique_id: trappegang_lys
  entities:
    - light.trappelys

- platform: group
  name: Do Lys
  unique_id: do_lys
  entities:
    - light.do_speillampe

- platform: group
  name: Bad Lys
  unique_id: bad_lys
  entities:
    - light.bad_speillampe
