#########################################
#         LYS GRUPPER                   #
#########################################

#########################################
#         LYS GRUPPER ROM               #
#########################################

- platform: group
  name: Pultlampe
  unique_id: pultlampe
  entities:
    - light.pultlampe_venstre
    - light.pultlampe_hoyre
