vanning_kjokken:
  name: Vanning Kjøkken Timer
  icon: mdi:timer

vanning_veranda_bed:
  name: Vanning Veranda Bed Timer
  icon: mdi:timer

vanning_veranda_blomster:
  name: Vanning Veranda Blomster Timer
  icon: mdi:timer
