esphome:
  name: sd
  friendly_name: sd

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "O3FQTQpsXrGuYRDTXzmIvE6sZZkwzK6UFjGNJsaJKyk="

ota:
  - platform: esphome
    password: "e263f44de01c9a188429a1f458d84854"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sd Fallback Hotspot"
    password: "4uAQOm6SKZgF"

captive_portal:
    